### ISSUE TITLE
Project owner and real name

### ISSUE THREAD

**Issue by 1995parham** [aiotrc/pm#2]
Pass project owner username & project real name when creating project.

**Comment by sajjadrahnama7** [comment]
As soon as possible

**Comment by 1995parham** [comment]
I think for downlink we will need project identification in loraserver.io

**Comment by sajjadrahnama7** [comment]
@1995parham done

**Comment by 1995parham** [comment]
Thanks 🙌

**Comment by sajjadrahnama7** [comment]
@1995parham why do you need project owner?

**Comment by 1995parham** [comment]
I think we can use it in order to notify the current user about the project owner user as it done in bash script by $USER
